---
title: "State Level Time Series Data"
author: "Tony Carilli"
date: "`r lubridate::today()`"
output: 
  html_document:
    df_print: paged
    
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "NA",
                      options(scipen = 999, digits = 3))
```

```{r libraries, message=FALSE}
library(tidyverse)
library(magrittr)
```

# Retrieve data

```{r retrieve data, warning=FALSE, message=FALSE}
covid_daily <- 
  covid19.analytics::covid19.US.data() %>% 
  select(-Country_Region)

# covid_daily 
```

# Clean the data

## Observations from states and dc only

```{r states}
covid_daily %<>% 
  filter(Province_State %in% c(state.name, "District of Columbia"))
```


## Tidy the data

```{r longer}
covid_daily %<>% 
  pivot_longer(-c(Province_State, Lat, Long_),
  names_to = "date",
  values_to = "value") %>% 
  mutate(date = lubridate::ymd(date))
```



## Add county names and fips based on Lat and Long_ 

```{r county-names}
covid_daily <- 
covid19.analytics::covid19.JHU.data() %>% 
  filter(Country_Region == "US") %>% 
  left_join(covid_daily, by = c("Lat", "Long_")) %>% 
  select(date, fips = FIPS, county = Admin2, state = Province_State.x, value)
```

`value` contains 2 observations per day confirmed and deaths

## Extract confirmed and deaths from value

```{r extract-confirmed-cases}
covid_daily %<>% 
  filter(!is.na(fips)) %>% # remove statewide observations
  arrange(date, fips) %>% 
  mutate(type = rep(c("confirmed", "deaths"),
                    length.out = length(fips))) %>% 
  pivot_wider(names_from = type,
              values_from = value)

# covid_daily
```

