---
title: "Social Capital and Covid-19"
author: "Carson"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    theme: cerulean
    highlight: tango
    code_folding: hide
indent: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Social Capital and Covid-19

## I Introduction
  
In light of the on-going Covid-19 pandemic, scholars are beginning to examine the relationship between social capital and the spread and prevention of Covid-19 (Wong and Kohler, 2020; Borgonovi and Andrieu, 2020; Borgonovi, Andrieu, and Subramanian, 2020; Wu, 2020; Wu et al., 2020; Bartscher et al., 2020; Durante et al., 2020).^[Putnam (2000: 19) defines social capital as the "connections among individuals---social networks and the norms of reciprocity and trustworthiness that arise from them."] The influence social capital has on health outcomes in general is well-studied (Putnam, xxxx), and there is even some recognition that social capital influences the spread of infectious diseases (H1N1, xxxx). While the emerging literature on social capital and Covid-19 generally shows that social capital encourages preventative behavior, few recognize the extent to which social capital complements formal, governmental public health responses like lockdown and stay-at-home orders. Without this recognition, the efficacy of social capital and formal public health rules tend to be overestimated, which can lead to poor public health policy.  

It is plausible that people with stronger social capital networks might have more interactions with each other, which could encourage infectious behavior. It is also plausible that greater social capital encourages preventative behavior via communal efforts to prevent infection, adopting new informal rules, and enforcing formal public health rules. Existing evidence suggests the latter effect is larger than the former. That is, people living in counties (in the United States) with more social capital reduced their mobility “earlier and to a higher degree” than people in counties with less social capital (Borgonovi and Andrieu (2020: xx; also, see Borgonovi, Andrieu, and Subramanian, 2020).^[Borgonovi, Andrieu, and Subramanian (2020) show that infection rates were initially higher in counties with more social capital, but transmission and mortality rates declined as people learned more about Covid-19. Similarly, Bartscher et al. (2020) suggests that the number of Covid-19 cases across Europe was initially higher in countries with higher social capital, but that cases increased at a slower rate in countries with higher social capital.] There is also suggestive evidence that people in areas with more social capital are more likely to follow formal public health rules, e.g., wearing face masks (Wu, 2020) and are more likely to have higher rates of testing (Wu et al., 2020).

Our study is the first to argue social capital is complementary to formal public health rules and that it exerts an independent effect on Covid-19 transmission. With state-level data on Covid-19 cases, social capital, and stringency---a measure of the severity of public health measures---we develop a panel model to assess these relative effects. Overall, we find social capital and stringency exert significant, independent effects on daily Covid-19 cases, and that higher social capital makes the effect of stringency larger for a given level of stringency. Consistent with the existing literature, social capital increases the number of daily cases and stringency decreases the number of daily cases, whereas the interaction between the two terms decreases the number of daily cases. Social capital by itself does not encourage preventative behavior; however, it bolsters the effect of stringency measures. Furthermore, we find that xxx is a more important component of social capital. That is, while the state-level social capital index has a consistent effect on daily Covid-19 cases, xxx is one of the most important components of that index.

The primary implication is that social capital plays an identifiable role in how people spread infectious diseases, which should be recognized in public health scholarship and policy. Whereas Bartscher et al. (2020) suggests social capital becomes less important once lockdown orders are issued, our results suggest that social capital plays a consistently complementary role with more formal rules regarding Covid-19---at least from March 1, 2020 to November 1, 2020. 

Yet, social capital is not a lever one person or a large group of people can toggle, so altering social capital is not a tractable policy option. Even though social capital bolsters formal rules, this does not necessarily suggest policymakers should target areas with less social capital, let alone double-down along the intensive margin (as suggested by Bartscher et al., 2020). Even though areas with less social capital will not experience the complementary effect social capital has on stringency, those areas might have fewer interactions in the first place which might leave them with fewer Covid-19 cases. In any event, the relationships between social capital, formal public health rules, and the spread of infectious diseases enhances our understanding of how people spread infectious diseases.

In addition to the emerging economic literature on Covid-19 and the relationship between social capital and Covid-19, this study also has implications for the larger economic literature on institutions and the extent to which formal and informal rules influence behavior. While many economists understand the role institutions have in creating incentives to engage in commercial activity (North, 1990; Baumol, 1990; Ostrom, 2005; Boettke and Coyne, 200x; Williamson, 2009; Storr, xxxx), the effects those institutions might have on behaviors related to preventative behavior are less clear despite recent work. For example, formal economic and political institutions, like the American Constitution, made it more difficult to develop public health bureaux---to provide filtered water and respond to disease outbreaks---in the late 19th and early 20th centuries (Troesken, 2015; Olmstead and Rhode, 2015). People might also be better able to respond to outbreaks *because* of the quality of their political and economic institutions. For example, Geloso and Pavlik (2020) find that people were better able to respond---avoid infection---to the Spanish Flu pandemic if they lived in areas with greater economic freedom. Geloso and Candela (2020) also show economic freedom fostered recovery from flu pandemics throughout the 20th century. Relatedly, individuals can alter the incentives and rules they face to provide mosquito-control (Carson, 2016; Carson, 2020a), and to encourage Covid-19 prevention (Carson, forthcoming). The present work on social capital adds to this emerging literature on how individuals create and enforce rules to encourage preventative behavior through their own interactions---in addition to but not necessarily from a centralized public health department.

Informal rules or social norms also influence behavior, e.g., pro-environmental behaviors (Farrow et al., 2017) (see, Brennan et al., 2014; and Bichierri, xxxx, for general treatments on social norms). Yet, few recognize the extent to which social norms influence behaviors related to the spread of infectious diseases (see, Carson, 2016, for one attempt). The present study develops a parsimonious synthesis between the role social norms play as a component of social capital and how they influence disease-related behaviors.

A related theme in the economics of institutions literature is that formal rules are partially dependent on supporting informal rules. The implication is that mimicking formal rules without the underlying cultural values and informal rules (or *metis* following Boettke, Coyne, Leeson, 2008) is not appropriate and likely to evince worse outcomes. Indeed, Carilli, Coyne, and Leeson (2008) show government-led attempts to foster social capital or create homogeneity---for example, through language laws or the creation of a civil court---create unintended, harmful effects. In the context of Covid-19, social capital throughout most of the United States is such that people support the formal public heath rules state governments adopt. While such rules are appropriate for the people who adopt them, given their governing bodies and rules, caution is required when considering merely adopting policies other states adopt. Even though there is a large degree of cultural homogeneity in the United States, the kind of formal rules adopted in Hawaii or in New York might be inappropriate for the people of Mississippi or in California, let alone in other countries. 

Another closely related theme in the economics of institutions is that formal rules and regulations might be a relevant alternative when trust is lacking (Williamson, 2009; Williamson, 2013; Davis and Williamson, 2016; Williamson, 2020; Cline and Williamson, 2019). However, our results suggest that social capital and formal public health rules complement each other. We do not find evidence that these mechanisms are substitutes.

## II Social Capital, Formal Rules, and Covid-19

Social capital can take various forms between individuals so as to encourage cooperation. Two of the main forms include *bridging* between people within a social network and *bonding* between people from different social networks.^[We do not take a stance as to which form of social capital is theoretically more or less relevant in the context Covid-19. We do, however, provide evidence below regarding the various measured components of social capital. [do any of these measures highlight the difference between bonding and bridging?]] There are also numerous explanations as to why social capital might influence health outcomes. People with greater access to social capital or in a network with stronger social capital might have more tangible assistance, e.g., money or health care; social norms that enforce healthy behaviors are probably more prevalent in areas with more social capital, e.g., don't take the last bite of food; people might have more of an ability to advance a political agenda to alter health policy when social capital is greater; and, finally, people might also have better immune systems as social capital strengthens (Putnam, 2000).

Regardless of the kind of social capital, we posit that individuals in areas with stronger social capital are more likely to engage in preventative behavior, which ultimately lowers the daily number of Covid-19 cases. To develop this, we focus on two counteracting effects. First, social capital necessarily lowers transactions costs between two or more people, which leads to more interactions, stronger relationships, and novel kinds of relationships. Interactions in areas with higher social capital do not necessarily take the form of physical interactions---where Covid-19 is more easily spread---but physical interactions are more likely. Indeed, Chamlee-Wright (xxxx) and Carilli, Coyne, and Leeson (2008) argue there is an entrepreneurial quality to the development of social capital, which tends to increase physical interactions. All else equal, the *face-to-face* effect increases the number of Covid-19 cases.

Second, social capital raises the private costs to individuals of breaking rules a group perceives as legitimate, namely formal and informal public health rules. Municipal face mask ordinances and state-wide lockdown orders are examples of the former kind of public health rules, while wearing a face mask whilst in any public setting and covering ones' mouth for a sneeze are examples of the latter kind.^[Whereas formal rules specify a primary directive and secondary qualifiers, a centralized enforcement mechanism, and it is a rule derived from some kind of governing body, informal rules might only specify a primary directive with few secondary qualifiers, enforcement is decentralized, and it is a rule derived from the normative attitudes of the individuals to which the rule applies (Brennan et al., 2014).] While informal rules are difficult to systematically measure in large groups, we focus on the relationship between formal rules and social capital below.^[See Carson (forthcoming) on the relevance of rules to encourage preventative behavior in the context of Covid-19.] 

Social capital encourages rule-following behavior because it raises the private cost to individuals of breaking rules. Given many people believe public health rules are legitimate and valuable, breaking those rules is taken as an affront punishable informally by a personal rebuke, a worsening reputation, a refusal of service, or fewer social contacts. More formal measures of enforcement and punishment are also relevant, e.g., calling a public health department or the police. Related, people are better able to monitor the behavior of others in areas with stronger social capital given the numerous social ties; this suggests that infractions are more likely to be discovered in areas with stronger social capital. Thus, as strong or severe as a formal public health rule is, social capital will encourage individuals to follow it. All else equal, this *dutiful* effect lowers the number of Covid-19 cases.

Accounting for these two factors of social capital---the *face-to-face* factor and the *dutiful* factor---suggests that if social capital lowers the number of cases, the *dutiful* factor outweighs the *face-to-face* factor. 

## III Data and Model

* Dependent Variable

  * Why do we focus on cases, not deaths?

* Independent Variable

## IV Results

Table 1 - Base Panel Regression Model of New cases as a function of stringency and stringency::social capital.

Table 2a - By Month
Table 2b - By every three months
Table 2c - eyeball date

Table 3 - IV

Table 4 - Controls and one-way fixed effects (time)

## V Conclusion
Notes:

* Social capital consistently influences infectious and preventative behaviors. 

* Informal rules like those found in social capital influence behavior and bolster formal rules.

* Policy implications are difficult to tease out given social capital is emergent. Social capital is a deeper notion than merely doing what an elected official tells us to do. Trusted advisers, business contacts, friends, and family comprise our social networks and capital.



While we can easily identify measures of social capital, e.g., the number of community centers or the percent of people who donate to charitable organizations, cultivating social capital---in the way it is meant in the literature---is not so simple. Perhaps for future outbreaks, we can discuss the role social capital might have and how to bolster that capital, but it seems unlikely that it will come from a centralized source.

* Future research should study the extent to which social capital erodes over time particularly because of formal rules that prevent interactions. That is, while we find social capital bolsters formal rules, those formal rules might extinguish the necessary parts of social capital given a longer duration or additional severity. This is especially once we recognize the cultural context within which social capital emerges, i.e., human interactions and the norms of proper behavior that develop. Formal rules that make such interactions more costly are likely to alter the costs and benefits people face such that existing social capital erodes (Carilli, Coyne, and Leeson, 2008) and alternative kinds of social capital will arise. Indeed, if formal rules prevent interactions that would have otherwise taken place, individuals realize less of a benefit from maintaining existing social ties. 

Alternatively, emphasis should be placed on providing quality information about Covid-19 transmission, as well as encouraging individuals to seek out relevant tests. Such measures encourage individuals to make decisions and *invest* in existing social ties according to their values.

* If two states have a stringency index of "6" - do they have the same policies? What are the potential differences? Same with social capital...